"use server";
import { db } from "@/lib/db";
import { requireAdmin, requireUser } from "@/lib/auth";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
function text(fd:FormData,key:string){return String(fd.get(key)||"").trim();} function int(fd:FormData,key:string,fallback=0){const n=Number(fd.get(key));return Number.isFinite(n)?Math.max(0,Math.floor(n)):fallback;}
export async function joinTournamentAction(fd:FormData){const user=await requireUser();const tournamentId=text(fd,"tournamentId");const tournament=await db.tournament.findUnique({where:{id:tournamentId},include:{_count:{select:{registrations:true}}}});if(!tournament||tournament.status!=="OPEN")redirect("/tournaments?error=Camp%20indisponível");if(tournament._count.registrations>=tournament.maxPlayers)redirect("/tournaments?error=Camp%20lotado");if(user.credits<tournament.entryCredits)redirect("/tournaments?error=Saldo%20insuficiente");const existing=await db.registration.findUnique({where:{userId_tournamentId:{userId:user.id,tournamentId}}});if(existing)redirect("/tournaments?error=Você%20já%20está%20inscrito");await db.$transaction([db.user.update({where:{id:user.id},data:{credits:{decrement:tournament.entryCredits}}}),db.registration.create({data:{userId:user.id,tournamentId}})]);revalidatePath("/dashboard");revalidatePath("/tournaments");redirect("/tournaments?success=Inscrição%20confirmada");}
export async function createTournamentAction(fd:FormData){await requireAdmin();const title=text(fd,"title"),startsAt=text(fd,"startsAt");if(title.length<3||!startsAt)redirect("/admin?error=Preencha%20nome%20e%20data");const slugBase=title.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");await db.tournament.create({data:{title,slug:`${slugBase}-${Date.now().toString(36)}`,description:text(fd,"description")||"Campeonato oficial AttoFlow.",mode:text(fd,"mode")||"Squad",map:text(fd,"map")||"Bermuda",maxPlayers:int(fd,"maxPlayers",48)||48,entryCredits:int(fd,"entryCredits"),prizeCredits:int(fd,"prizeCredits"),startsAt:new Date(startsAt),status:"OPEN",rules:text(fd,"rules")||"Fair play obrigatório."}});revalidatePath("/admin");revalidatePath("/tournaments");redirect("/admin?success=Camp%20criado");}
export async function updateUserStatusAction(fd:FormData){const admin=await requireAdmin();const userId=text(fd,"userId");const status=text(fd,"status")==="BLOCKED"?"BLOCKED":"ACTIVE";if(userId===admin.id&&status==="BLOCKED")redirect("/admin?error=Você%20não%20pode%20bloquear%20a%20própria%20conta");await db.user.update({where:{id:userId},data:{status}});revalidatePath("/admin");}
export async function updateTournamentStatusAction(fd:FormData){await requireAdmin();const tournamentId=text(fd,"tournamentId");const allowed=["DRAFT","OPEN","LIVE","FINISHED","CANCELLED"] as const;const requested=text(fd,"status") as (typeof allowed)[number];const status=allowed.includes(requested)?requested:"DRAFT";await db.tournament.update({where:{id:tournamentId},data:{status}});revalidatePath("/admin");revalidatePath("/tournaments");}
